name: quantumlab
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # Quantum
  - qiskit>=2.2,<3
  - qiskit-aer>=0.17,<1

  # Scientific
  - numpy>=2.3,<3
  - matplotlib>=3.10,<4

  # Jupyter
  - jupyter>=1.1,<2
  - jupyterlab>=4.5,<5
  - ipykernel>=7,<8

  # Optional
  - scipy>=1.14,<2
  - pandas>=2.2,<3